Part 18/1 - Final task: Badges
Vicxwild/test-guru pull request #20
Opened 2023-03-23 09:46 UTC by Vicxwild

2023-03-24 18:33 UTC, BubuntuClu requested changes

2023-03-24 18:33 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    @current_user.tests.by_category("Frontend").uniq == Test.by_category("Frontend").available
лучше сравнить цифры, чем объекты. добавь еще `count`

2023-03-24 18:33 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +  def backend_king_rule
этот метод тот же самый что и frontend_king_rule. различается только параметром для поиска.
перемести парамтр из хардкода в коде, в сам бадж. так ты при создании баджа сможешь просто указать какую категорию проверять надо и не надо будет правки в код вносить

2023-03-24 18:33 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    @test_passage.percentage_success == 100
как эта проверка отвечает на вопрос "пройден ли тест с первого раза?"?
ты просто проверяешь что тест был пройден на 100 процентов

2023-03-24 18:33 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    (@earned_badge << Badge.find_by(title: "Backend king")) if backend_king_rule
при увеличиении количества правил, тут будет разрастаться это дерево проверок.
можно название правила тоже поместить в сам бадж, а уже в коде применить немного метапрограммирования и по названию правила вызывать нужный метод

2023-03-24 18:33 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    (@earned_badge << Badge.find_by(title: "First try")) if first_try_rule
может так случиться что на какое-то прохождение тебе придеться сходить в БД несколько раз, чтоб найти нужный бадж, чтобы запихнуть его в массив. давай за один запрос получим нужные баджи. ну и небольшая подсказка, тебе это нужно будет чтобы реализовать код, по замечанию выше

2023-03-25 10:48 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +    @test_passage.percentage_success == 100
Изменил название, так как подразумевал иную реализацию - проверка на безошибочное прохождение

2023-03-25 10:53 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +    @current_user.tests.by_category("Frontend").uniq == Test.by_category("Frontend").available
Исправил

2023-03-25 18:51 UTC, BubuntuClu requested changes

2023-03-25 18:51 UTC, BubuntuClu commented on app/services/badges/frontend_king_rule.rb
> +module Badges
это все еще тот же код что и у бэкенд баджа. они отличаются только словом backend/frontend. сделай это параметром в методе. так тебе не надо будет на каждую категорию заводить правило. а можно будет создать бадж с этим правилом и указать другую категорию

2023-03-25 18:51 UTC, BubuntuClu commented on app/services/badges/flawless_victory_rule.rb
> +  class FlawlessVictoryRule
это все еще не прохождение теста с первого раза. ты можешь сделать свое правило, это не запрещается, но все равно надо реализовать логику про прохождение теста с первого раза

2023-03-25 18:51 UTC, BubuntuClu commented on app/services/badges/backend_king_rule.rb
> +      def title
это где-то используется? что-то я не нашел

2023-03-25 18:51 UTC, BubuntuClu commented on db/migrate/20230324110841_change_url_on_picture_link_attribute_in_badges.rb
> +class ChangeUrlOnPictureLinkAttributeInBadges < ActiveRecord::Migration[6.1]
ты еще не смержил ветку, можешь откатить миграцию создания таблицы и поправить все названия колонок там. не надо плодить лишние миграции, когда ты еще можешь поправить все нужные вещи

2023-03-25 18:51 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    RULES.map do |rule|
если добавишь параметры в правила, то у тебя баджей будет больше чем правил. такой перебор не будет работать правильно

2023-03-28 10:04 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +  def backend_king_rule
Исправил

2023-03-28 10:05 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +    (@earned_badge << Badge.find_by(title: "First try")) if first_try_rule
Исправил

2023-03-28 10:05 UTC, Vicxwild commented on app/services/badges/frontend_king_rule.rb
> +module Badges
Исправил

2023-03-28 10:06 UTC, Vicxwild commented on app/services/badges/flawless_victory_rule.rb
> +  class FlawlessVictoryRule
Добавил такое правило

2023-03-28 10:06 UTC, Vicxwild commented on app/services/badges/backend_king_rule.rb
> +      def title
Сейчас уже удалил этот метод

2023-03-28 10:06 UTC, Vicxwild commented on db/migrate/20230324110841_change_url_on_picture_link_attribute_in_badges.rb
> +class ChangeUrlOnPictureLinkAttributeInBadges < ActiveRecord::Migration[6.1]
Удалил лишнюю миграцию, переписал все прямо в первой

2023-03-28 10:07 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +    RULES.map do |rule|
Изменил перебор

2023-03-28 17:03 UTC, BubuntuClu requested changes

2023-03-28 17:03 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :description, :picture_link, :rule_type, :category, :level)
`:category, :level` это надо разместить в один общий параметр. если на каждый новый отличающийся бадж добавлять новый столбец в БД, то таблица будет огромная

2023-03-28 17:03 UTC, BubuntuClu commented on app/services/badges/king_rule.rb
> +        if badge_category_title == current_test_category_title
лучше написать `return if badge_category_title != current_test_category_title` чтобы не делать вложенный код

2023-03-28 17:03 UTC, BubuntuClu commented on app/services/badges/king_rule.rb
> +          user.tests.by_category(badge_category_title).uniq.count == Test.by_category(badge_category_title).available.count
в запросе на поиск пройденных тестов пользователя нет проверки на то что тесты эти пройдены успешно. ты учитываешь все проверки, а это неправильно

2023-03-28 17:03 UTC, BubuntuClu commented on app/services/badges/level_rule.rb
> +          user.tests.by_level(rule_level).uniq.count == Test.by_level(rule_level).available.count
тут тоже самое что и в категориях. надо учитывать только пройденные успешно тесты

2023-03-28 17:08 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +    @user.badges << Badge.where(title: new_achievements)
ты в методе выше итерируешь по всем баджам. находишь заголовки баджей и потом ищешь список баджей по этим заговлокам. выглядит не очень логично.

в каждый момент времени(итерация по баджам) ты имеешь нужный тебе бадж, не надо ходить за ним потом в БД отдельным действием

2023-03-28 17:08 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +  def check_new_badges
обычно в рубях у сервиса есть только метод `call`(не считая инициализатор), который делает какую-то логику. переименуй чтобы по-тихоньку привыкать к неймингу

2023-03-29 08:36 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +    (@earned_badge << Badge.find_by(title: "Backend king")) if backend_king_rule
Исправил
Сначала не понял о чем речь

2023-03-29 10:51 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +  def check_new_badges
Исправил

2023-03-29 11:10 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +    @user.badges << Badge.where(title: new_achievements)
Исправил, добавил `@badges = Badge.all` в конструктор

2023-03-29 13:04 UTC, Vicxwild commented on app/services/badges/king_rule.rb
> +          user.tests.by_category(badge_category_title).uniq.count == Test.by_category(badge_category_title).available.count
Добавил скоуп в модель Тест, который проверяет успешность тестов и уникальность

2023-03-29 13:04 UTC, Vicxwild commented on app/services/badges/level_rule.rb
> +          user.tests.by_level(rule_level).uniq.count == Test.by_level(rule_level).available.count
Аналогично

2023-03-29 13:23 UTC, Vicxwild commented on app/services/badges/king_rule.rb
> +        if badge_category_title == current_test_category_title
Исправил

2023-03-29 14:25 UTC, Vicxwild commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :description, :picture_link, :rule_type, :category, :level)
Исправил

2023-03-29 17:10 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    save!
бэнг методы стоит оборачивать в rescue блок, иначе упадет сохранение и потащет за собой приложение

2023-03-29 17:10 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +      badge if rule.suitable?(test_passage, badge)
а что если просто `@user.badges << badge if rule.suitable?(test_passage, badge)`?
зачем тебе хранить массив баджей чтобы его передать в другой метод, когда ты можешь сразу запихнуть бадж в пользователя?

2023-03-29 17:10 UTC, BubuntuClu commented on app/services/badges/king_rule.rb
> +        user.tests.by_category(badge_category_title).by_success.count == Test.by_category(badge_category_title).available.count
тут стоит переделать на поиск тестов через тест пассаж. у тебя сейчас тут много запросов происходит. сначала находишь все тесты, потом туда джойнишь категории. потом к результату джофнишь прохождения.

можно отфильтровать сразу прохождения по пользователю и тестам(поулчить из `Test.by_category(badge_category_title).available.ids`) и отфильтровать по успеху. так запрос будет оптимальней

2023-03-29 17:10 UTC, BubuntuClu commented on app/services/badges/first_try_rule.rb
> +      def suitable?(test_passage, badge)
там где параметр не используется пиши перед ним `_`. `_badge`

2023-03-29 17:10 UTC, BubuntuClu commented on app/services/badge_achievement_service.rb
> +      badge if rule.suitable?(test_passage, badge)
выглядит так что тебе в методы не надо передаваь сам бадж, достаточно передать параметр баджа

2023-03-29 17:10 UTC, BubuntuClu commented on app/services/badges/level_rule.rb
> +        user.tests.by_level(rule_level).by_success.count == Test.by_level(rule_level).available.count
тоже самое и тут. сделай запрос относительно прохождений

2023-03-30 08:27 UTC, Vicxwild commented on app/models/test_passage.rb
> +    save!
Добавил rescue блок

2023-03-30 09:12 UTC, Vicxwild commented on app/services/badge_achievement_service.rb
> +      badge if rule.suitable?(test_passage, badge)
Исправил

2023-03-30 09:13 UTC, Vicxwild commented on app/services/badges/first_try_rule.rb
> +      def suitable?(test_passage, badge)
Исправил

2023-03-30 11:56 UTC, dmakhmutov commented on app/services/badges/first_try_rule.rb
> +        (user.tests.where('tests.id = ?', test_id).count == 1) && (test_passage.success == true)
я бы всё таки отрефактроли и добавил `test_passage.success?`, просто потому что DRY и не придётся везде писать кострукции типа == true, != true

2023-03-30 11:56 UTC, dmakhmutov commented on app/services/badges/first_try_rule.rb
> +        (user.tests.where('tests.id = ?', test_id).count == 1) && (test_passage.success == true)
ну и вторая проверка не нужна, раз [тыц](https://github.com/Vicxwild/test-guru/pull/20/files#diff-f347030c6cf2dea16d7e978d154b236e0cbf8eb8fbf96b1986504e646defd2a4R8)

2023-03-30 11:56 UTC, dmakhmutov commented on app/services/badges/first_try_rule.rb
> +        return if test_passage.success != true
если ты используешь методы с вопросом, то возьми за правило возвращать boolean
return false if ....

2023-03-30 11:57 UTC, dmakhmutov commented on app/services/badges/first_try_rule.rb
> +        (user.tests.where('tests.id = ?', test_id).count == 1) && (test_passage.success == true)
в целом эта проверка не нужна, т.к. если тест не пройден, то ни каких бейджей мы вешать не должны

2023-03-30 12:57 UTC, merged