Part 18/2 - Final task: Timer
Vicxwild/test-guru pull request #21
Opened 2023-03-30 14:06 UTC by Vicxwild

2023-03-31 17:18 UTC, BubuntuClu requested changes

2023-03-31 17:18 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +    test.time_limit == 0 ? t('admin.tests.test.no_timer') : test.time_limit
это очень плохая практика, когда метод тебе может вернуть ответ в двух разных типах данных. в одном случае строка, в другом интеджер. надо переделать

2023-03-31 17:18 UTC, BubuntuClu commented on app/javascript/utilities/timer.js
> +          window.location.href = window.location.href + '/result'
сделай лучше сабмит формы, чтобы отработала вся логика метода `update`. вдруг это просто последний вопрос, а остальные все правильные, что теперь его без баджа отсавить если все вдруг что?

2023-04-03 10:30 UTC, Vicxwild commented on app/javascript/utilities/timer.js
> +          window.location.href = window.location.href + '/result'
Сейчас пытался реализовать это функционал, но перечитал задание: "При истечении времени таймера тест считается не пройденным"
Поэтому это не бьется с моей логикой выдачи баджей, что пользователь получает их только при успешном прохождении теста. Приступаю к rack

2023-04-03 10:30 UTC, Vicxwild commented on app/helpers/tests_helper.rb
> +    test.time_limit == 0 ? t('admin.tests.test.no_timer') : test.time_limit
Исправил

2023-04-03 10:34 UTC, merged