add: config params, version, about pages, entities
Vicxwild/test-guru pull request #3
Opened 2022-11-02 17:39 UTC by Vicxwild

2022-11-03 07:04 UTC, BubuntuClu requested changes

2022-11-03 07:04 UTC, BubuntuClu commented on config/application.rb
> +    config.i18n.default_locale = :"en-US"
давай просто `:en`

2022-11-03 07:04 UTC, BubuntuClu commented on public/about/author.html
> +          Link to github: github.com/Vicxwild
это должна быть ссылка, на которую кликаешь и переходишь на нужную страницу. страница на сторонние ресурсы должны открываться в новой вкладке

2022-11-03 07:04 UTC, BubuntuClu commented on public/about/index.html
> +<!DOCTYPE html>
эта страница просто `publuc/about.html`
на ней доджна быть ссылка на страницу об авторе и внешняя ссылка на сайт школы

2022-11-03 07:04 UTC, BubuntuClu commented on config/initializers/version.rb
> +    VERSION = "0.1.0"
почему константа, а не метод?

2022-11-03 15:55 UTC, Vicxwild commented on config/initializers/version.rb
> +    VERSION = "0.1.0"
А почему должен быть метод? Каждый раз будет необходимо инициализировать новый экземпляр класса, чтобы узнать о версии?

2022-11-03 16:50 UTC, BubuntuClu commented on config/initializers/version.rb
> +    VERSION = "0.1.0"
это может быть метод класса и тогда не надо будет делать инициализацию.

2022-11-03 16:50 UTC, BubuntuClu commented on config/initializers/version.rb
> +      VERSION
почему тут используешь константу, а не просто строка в методе?

2022-11-04 09:47 UTC, Vicxwild commented on config/initializers/version.rb
> +      VERSION
Изначально нашел такой пример на stackoverflow, нет конкретной причины
Исправлю в следующем коммите

2022-11-04 09:56 UTC, merged