Rails Views
Vicxwild/test-guru pull request #9
Opened 2023-01-13 10:08 UTC by Vicxwild

2023-01-13 20:13 UTC, BubuntuClu requested changes

2023-01-13 20:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_path(@current_test)
метод надо использовать, а не переменную

2023-01-13 20:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def current_test
почему метод приватный? ты же его хэлпером сделал, и во вьюхах используешь, какой смысл в приватную секцию в этом случае его помещать?

2023-01-13 20:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def rescue_with_question_not_foun
`founD`

2023-01-13 20:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = current_test.questions.find(params[:id])
поиск вопроса повторяется в нескольких экшенах, как минимум в отдельный метод надо вынести, раз от колбэков отказываешься. в контроллераз нахождение объектов не так страшно размещать в колбэках. вот колбэки в моделях это уже хуже

2023-01-13 20:13 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render plain: "The questions was not found"
ты же ищешь конкретный вопрос, когда ошибку можешь словить, тогда число должно быть единственное.
а еще можно получить ошибку not_found если указать несуществующий тест

2023-01-15 11:36 UTC, Vicxwild commented on app/controllers/questions_controller.rb
> +    @question = current_test.questions.find(params[:id])
Вынес в отдельный метод
Лучше понял как работает `helper_method`
Спасибо

2023-01-15 11:36 UTC, Vicxwild commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_path(@current_test)
Исправил

2023-01-15 11:37 UTC, Vicxwild commented on app/controllers/questions_controller.rb
> +  def current_test
Разобрался
Исправил

2023-01-15 11:38 UTC, Vicxwild commented on app/controllers/questions_controller.rb
> +    render plain: "The questions was not found"
Исправил

2023-01-15 11:40 UTC, Vicxwild commented on app/controllers/questions_controller.rb
>    def rescue_with_question_not_foun
Исправил

2023-01-15 11:41 UTC, Vicxwild commented on app/controllers/questions_controller.rb
> +    @question = current_test.questions.find(params[:id])
Только не понял про коллбеки в моделях

2023-01-20 08:23 UTC, merged